// QuizKanji.jsx
import FlashcardGame from "../components/FlashcardGame.jsx"

// front = kanji, back = significado principal, sub = on読み · kun読み
const KANJIS = [
  // Números
  { front:"一", back:"uno", sub:"イチ · ひと(つ)" },
  { front:"二", back:"dos", sub:"ニ · ふた(つ)" },
  { front:"三", back:"tres", sub:"サン · みっ(つ)" },
  { front:"四", back:"cuatro", sub:"シ/ヨン · よっ(つ)" },
  { front:"五", back:"cinco", sub:"ゴ · いつ(つ)" },
  { front:"六", back:"seis", sub:"ロク · むっ(つ)" },
  { front:"七", back:"siete", sub:"シチ/ナナ · なな(つ)" },
  { front:"八", back:"ocho", sub:"ハチ · やっ(つ)" },
  { front:"九", back:"nueve", sub:"キュウ/ク · ここの(つ)" },
  { front:"十", back:"diez", sub:"ジュウ · とお" },
  { front:"百", back:"cien", sub:"ヒャク" },
  { front:"千", back:"mil", sub:"セン" },
  { front:"万", back:"diez mil", sub:"マン" },
  { front:"円", back:"yen / círculo", sub:"エン · まる(い)" },
  { front:"半", back:"mitad", sub:"ハン · なか(ば)" },
  // Tiempo
  { front:"日", back:"día / sol", sub:"ニチ/ジツ · ひ" },
  { front:"月", back:"mes / luna", sub:"ゲツ/ガツ · つき" },
  { front:"年", back:"año", sub:"ネン · とし" },
  { front:"時", back:"hora / tiempo", sub:"ジ · とき" },
  { front:"分", back:"minuto / dividir", sub:"フン/プン · わか(る)" },
  { front:"午", back:"mediodía", sub:"ゴ" },
  { front:"前", back:"delante / antes", sub:"ゼン · まえ" },
  { front:"後", back:"después / detrás", sub:"ゴ/コウ · あと/うしろ" },
  { front:"毎", back:"cada / todo", sub:"マイ" },
  { front:"今", back:"ahora / este", sub:"コン/キン · いま" },
  { front:"先", back:"antes / primero", sub:"セン · さき" },
  { front:"朝", back:"mañana", sub:"チョウ · あさ" },
  { front:"夕", back:"atardecer", sub:"セキ · ゆう" },
  { front:"夜", back:"noche", sub:"ヤ · よる" },
  { front:"春", back:"primavera", sub:"シュン · はる" },
  { front:"夏", back:"verano", sub:"カ · なつ" },
  { front:"秋", back:"otoño", sub:"シュウ · あき" },
  { front:"冬", back:"invierno", sub:"トウ · ふゆ" },
  { front:"昨", back:"ayer / pasado", sub:"サク" },
  { front:"去", back:"pasar / pasado", sub:"キョ · さ(る)" },
  // Direcciones
  { front:"上", back:"arriba / encima", sub:"ジョウ · うえ" },
  { front:"下", back:"abajo / debajo", sub:"カ/ゲ · した" },
  { front:"中", back:"dentro / centro", sub:"チュウ · なか" },
  { front:"外", back:"fuera / exterior", sub:"ガイ · そと" },
  { front:"右", back:"derecha", sub:"ウ/ユウ · みぎ" },
  { front:"左", back:"izquierda", sub:"サ · ひだり" },
  { front:"東", back:"este", sub:"トウ · ひがし" },
  { front:"西", back:"oeste", sub:"セイ · にし" },
  { front:"南", back:"sur", sub:"ナン · みなみ" },
  { front:"北", back:"norte", sub:"ホク · きた" },
  { front:"間", back:"entre / intervalo", sub:"カン · あいだ" },
  // Naturaleza
  { front:"山", back:"montaña", sub:"サン · やま" },
  { front:"川", back:"río", sub:"セン · かわ" },
  { front:"田", back:"campo / arrozal", sub:"デン · た" },
  { front:"木", back:"árbol / madera", sub:"モク/ボク · き" },
  { front:"林", back:"bosquecillo", sub:"リン · はやし" },
  { front:"森", back:"bosque", sub:"シン · もり" },
  { front:"花", back:"flor", sub:"カ · はな" },
  { front:"空", back:"cielo / vacío", sub:"クウ · そら" },
  { front:"雨", back:"lluvia", sub:"ウ · あめ" },
  { front:"天", back:"cielo / paraíso", sub:"テン" },
  { front:"気", back:"espíritu / energía", sub:"キ" },
  { front:"火", back:"fuego", sub:"カ · ひ" },
  { front:"水", back:"agua", sub:"スイ · みず" },
  { front:"土", back:"tierra / suelo", sub:"ド/ト · つち" },
  { front:"石", back:"piedra", sub:"セキ · いし" },
  { front:"風", back:"viento", sub:"フウ · かぜ" },
  { front:"雪", back:"nieve", sub:"セツ · ゆき" },
  { front:"犬", back:"perro", sub:"ケン · いぬ" },
  { front:"猫", back:"gato", sub:"ビョウ · ねこ" },
  { front:"魚", back:"pez / pescado", sub:"ギョ · さかな" },
  { front:"牛", back:"vaca", sub:"ギュウ · うし" },
  { front:"鳥", back:"pájaro", sub:"チョウ · とり" },
  // Personas
  { front:"人", back:"persona", sub:"ジン/ニン · ひと" },
  { front:"女", back:"mujer", sub:"ジョ/ニョ · おんな" },
  { front:"男", back:"hombre", sub:"ダン/ナン · おとこ" },
  { front:"子", back:"niño / hijo", sub:"シ/ス · こ" },
  { front:"父", back:"padre", sub:"フ · ちち" },
  { front:"母", back:"madre", sub:"ボ · はは" },
  { front:"兄", back:"hermano mayor", sub:"ケイ/キョウ · あに" },
  { front:"姉", back:"hermana mayor", sub:"シ · あね" },
  { front:"弟", back:"hermano menor", sub:"テイ · おとうと" },
  { front:"妹", back:"hermana menor", sub:"マイ · いもうと" },
  { front:"友", back:"amigo/a", sub:"ユウ · とも" },
  { front:"私", back:"yo", sub:"シ · わたし" },
  { front:"名", back:"nombre / fama", sub:"メイ/ミョウ · な" },
  // Acciones
  { front:"食", back:"comer / comida", sub:"ショク · たべる" },
  { front:"飲", back:"beber", sub:"イン · のむ" },
  { front:"見", back:"ver / mirar", sub:"ケン · みる" },
  { front:"行", back:"ir", sub:"コウ/ギョウ · いく" },
  { front:"来", back:"venir", sub:"ライ · くる" },
  { front:"帰", back:"volver / regresar", sub:"キ · かえる" },
  { front:"読", back:"leer", sub:"ドク · よむ" },
  { front:"書", back:"escribir", sub:"ショ · かく" },
  { front:"聞", back:"escuchar", sub:"ブン/モン · きく" },
  { front:"話", back:"hablar", sub:"ワ · はなす" },
  { front:"言", back:"decir / palabra", sub:"ゲン/ゴン · いう" },
  { front:"起", back:"levantarse", sub:"キ · おきる" },
  { front:"寝", back:"dormir", sub:"シン · ねる" },
  { front:"使", back:"usar", sub:"シ · つかう" },
  { front:"買", back:"comprar", sub:"バイ · かう" },
  { front:"売", back:"vender", sub:"バイ · うる" },
  { front:"好", back:"gustar / querer", sub:"コウ · すき" },
  { front:"乗", back:"subir / montar", sub:"ジョウ · のる" },
  { front:"歩", back:"caminar", sub:"ホ · あるく" },
  { front:"走", back:"correr", sub:"ソウ · はしiru" },
  { front:"働", back:"trabajar", sub:"ドウ · はたらく" },
  // Lugares
  { front:"家", back:"casa / familia", sub:"カ/ケ · いえ/うち" },
  { front:"学", back:"estudiar", sub:"ガク · まなぶ" },
  { front:"校", back:"escuela", sub:"コウ" },
  { front:"駅", back:"estación de tren", sub:"エキ" },
  { front:"店", back:"tienda", sub:"テン · みせ" },
  { front:"会", back:"reunión / encontrarse", sub:"カイ/エ · あう" },
  { front:"社", back:"empresa / santuario", sub:"シャ · やしろ" },
  { front:"国", back:"país", sub:"コク · くに" },
  { front:"寺", back:"templo budista", sub:"ジ · てら" },
  { front:"病", back:"enfermedad", sub:"ビョウ · やむ" },
  { front:"院", back:"institución", sub:"イン" },
  // Descripción
  { front:"大", back:"grande", sub:"ダイ/オオ · おおきい" },
  { front:"小", back:"pequeño", sub:"ショウ · ちいさい" },
  { front:"高", back:"alto / caro", sub:"コウ · たかい" },
  { front:"安", back:"barato / tranquilo", sub:"アン · やすい" },
  { front:"新", back:"nuevo", sub:"シン · あたらしい" },
  { front:"古", back:"viejo / antiguo", sub:"コ · ふるい" },
  { front:"白", back:"blanco", sub:"ハク · しろ" },
  { front:"黒", back:"negro", sub:"コク · くろ" },
  { front:"赤", back:"rojo", sub:"セキ · あか" },
  { front:"青", back:"azul / verde", sub:"セイ · あお" },
  { front:"長", back:"largo / jefe", sub:"チョウ · なが(い)" },
  { front:"短", back:"corto", sub:"タン · みじか(い)" },
  { front:"早", back:"temprano / rápido", sub:"ソウ · はや(い)" },
  { front:"多", back:"mucho / muchos", sub:"タ · おおい" },
  { front:"少", back:"poco / joven", sub:"ショウ · すく(ない)" },
  { front:"明", back:"brillante / claro", sub:"メイ/ミョウ · あかるい" },
  { front:"暗", back:"oscuro", sub:"アン · くら(い)" },
  { front:"広", back:"amplio", sub:"コウ · ひろ(い)" },
  { front:"強", back:"fuerte", sub:"キョウ · つよ(い)" },
  { front:"弱", back:"débil", sub:"ジャク · よわ(い)" },
  // Estudio
  { front:"語", back:"idioma / palabra", sub:"ゴ" },
  { front:"文", back:"texto / escritura", sub:"ブン" },
  { front:"字", back:"letra / kanji", sub:"ジ" },
  { front:"漢", back:"chino / Han", sub:"カン" },
  { front:"勉", back:"esforzarse", sub:"ベン" },
  { front:"問", back:"pregunta", sub:"モン · とう" },
  { front:"答", back:"respuesta", sub:"トウ · こたえる" },
  // Cuerpo
  { front:"体", back:"cuerpo", sub:"タイ · からだ" },
  { front:"頭", back:"cabeza", sub:"トウ/ズ · あたま" },
  { front:"目", back:"ojo", sub:"モク/ボク · め" },
  { front:"耳", back:"oreja", sub:"ジ · みみ" },
  { front:"口", back:"boca", sub:"コウ/ク · くち" },
  { front:"手", back:"mano", sub:"シュ · て" },
  { front:"足", back:"pie / pierna", sub:"ソク · あし" },
  { front:"心", back:"corazón / mente", sub:"シン · こころ" },
  { front:"顔", back:"cara", sub:"ガン · かお" },
  // Transporte
  { front:"電", back:"electricidad", sub:"デン" },
  { front:"車", back:"coche / vehículo", sub:"シャ · くるま" },
  { front:"道", back:"camino / vía", sub:"ドウ · みち" },
  { front:"旅", back:"viaje", sub:"リョ · たび" },
  { front:"船", back:"barco", sub:"セン · ふね" },
  { front:"線", back:"línea / vía", sub:"セン" },
  // Comida
  { front:"茶", back:"té", sub:"チャ" },
  { front:"肉", back:"carne", sub:"ニク" },
  { front:"米", back:"arroz", sub:"ベイ/マイ · こめ" },
  { front:"本", back:"libro / origen", sub:"ホン · もと" },
  { front:"薬", back:"medicamento", sub:"ヤク · くすり" },
]

export default function QuizKanji() {
  return (
    <FlashcardGame
      title="Quiz Kanji N5"
      titleJp="漢字 N5"
      accentColor="#7a5c00"
      cards={KANJIS}
    />
  )
}
